export const definitions = {
  'node.d.ts': 'https://unpkg.com/@types/node/index.d.ts',
  'preact.d.ts': 'https://unpkg.com/preact/src/preact.d.ts',
  'three.d.ts': 'https://unpkg.com/@types/three/index.d.ts',
  'detector.d.ts': 'https://unpkg.com/@types/three/detector.d.ts',
  'three-FirstPersonControls.d.ts':
    'https://unpkg.com/@types/three@0.84.3/three-FirstPersonControls.d.ts',
  'three-canvasrenderer.d.ts': 'https://unpkg.com/@types/three@0.84.3/three-canvasrenderer.d.ts',
  'three-colladaLoader.d.ts': 'https://unpkg.com/@types/three@0.84.3/three-colladaLoader.d.ts',
  'three-copyshader.d.ts': 'https://unpkg.com/@types/three@0.84.3/three-copyshader.d.ts',
  'three-css3drenderer.d.ts': 'https://unpkg.com/@types/three@0.84.3/three-css3drenderer.d.ts',
  'three-ctmloader.d.ts': 'https://unpkg.com/@types/three@0.84.3/three-ctmloader.d.ts',
  'three-editorcontrols.d.ts': 'https://unpkg.com/@types/three@0.84.3/three-editorcontrols.d.ts',
  'three-effectcomposer.d.ts': 'https://unpkg.com/@types/three@0.84.3/three-effectcomposer.d.ts',
  'three-maskpass.d.ts': 'https://unpkg.com/@types/three@0.84.3/three-maskpass.d.ts',
  'three-octree.d.ts': 'https://unpkg.com/@types/three@0.84.3/three-octree.d.ts',
  'three-orbitcontrols.d.ts': 'https://unpkg.com/@types/three@0.84.3/three-orbitcontrols.d.ts',
  'three-orthographictrackballcontrols.d.ts':
    'https://unpkg.com/@types/three@0.84.3/three-orthographictrackballcontrols.d.ts',
  'three-projector.d.ts': 'https://unpkg.com/@types/three@0.84.3/three-projector.d.ts',
  'three-renderpass.d.ts': 'https://unpkg.com/@types/three@0.84.3/three-renderpass.d.ts',
  'three-shaderpass.d.ts': 'https://unpkg.com/@types/three@0.84.3/three-shaderpass.d.ts',
  'three-trackballcontrols.d.ts': 'https://unpkg.com/@types/three@0.84.3/three-trackballcontrols.d.ts',
  'three-transformcontrols.d.ts': 'https://unpkg.com/@types/three@0.84.3/three-transformcontrols.d.ts',
  'three-vrcontrols.d.ts': 'https://unpkg.com/@types/three@0.84.3/three-vrcontrols.d.ts',
  'three-vreffect.d.ts': 'https://unpkg.com/@types/three@0.84.3/three-vreffect.d.ts',
  'pixi.js.d.ts': 'https://unpkg.com/@types/pixi.js@4.4.1/index.d.ts',
  'regl.d.ts': 'https://raw.githubusercontent.com/jmfirth/DefinitelyTyped/regl-support/types/regl/index.d.ts',
  'gl-matrix.d.ts': 'https://unpkg.com/@types/gl-matrix@2.2.34/index.d.ts',
};